### PR TITLE
feat(nodejs): change image to alpine base image

### PR DESCRIPTION
**Pull request by vimtaai**
EME-2820

Co-authored-by: Gabor Soos <gabor.soos@emarsys.com>

### CODE REVIEW

**Comment by vimtaai** [comment]
The `node:14-alpine` base image has some vulnerabilities in Protecode. Moving to a pure `alpine` base image solves the issue.

**Comment by iben12** [comment]
How do you use specific version of NodeJS engine? Am I missing something?

**Comment by iben12** [comment]
While we're at it, we could remove `dumb-init`, which is actually not needed. The best practice is to start app with `node app.js` instead of `npm start` and this ensures your app gets all signals directly.

**Comment by vimtaai** [comment]
You can specify with a version in the `apk add` command like so: `nodejs=14.17.6-r0`.

**Comment by vimtaai** [comment]
@iben12 I updated it with a node-version and removed dumb-init

**Comment by iben12** [comment]
I mean ATM our apps use anything between v12 and v16. The actual package version is determined by the alpine version ([here](https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.12)).

I think we need to address that. I understand it's best every app is on the current LTS release, but I'm not sure it's viable.

**Comment by vimtaai** [comment]
If we use the latest alpine image then we should be able to install a specific node version, right?

**Comment by iben12** [comment]
That would fit every team. I think devs would be against that alpine determines which NodeJS version they should use. There are new features or breaking changes that may influence which one they use.

They will be forced to move away from old versions anyway, because the unsupported versions will have their own unfixed vulnerabilities in the node runtime itself.

**Comment by vimtaai** [comment]
How about now. We can specify a major version, but it should add the latest from that

**Comment by vimtaai** [comment]
https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Holding_a_specific_package_back

**Comment by iben12** [comment]
Do you think it works for other than 14?

Because it breaks for me on v12:
```
 > [2/2] RUN apk add --update-cache       nano       nodejs=~12 &&     rm -rf /var/cache/apk/*:                                                                                              
#5 0.169 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz                                                                                                      
#5 0.722 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
#5 1.054 ERROR: unable to select packages:
#5 1.066   nodejs-14.17.6-r0:
#5 1.066     breaks: world[nodejs~12]
```
Or v15:
```
 > [2/2] RUN apk add --update-cache       nano       nodejs=~15 &&     rm -rf /var/cache/apk/*:                                                                                              
#5 0.170 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
#5 0.406 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
#5 0.622 ERROR: unable to select packages:
#5 0.635   nodejs-14.17.6-r0:
#5 0.635     breaks: world[nodejs~15]
```

**Comment by vimtaai** [comment]
Yeah, it seems like that the APK repository only has one version of NodeJs... 😢  That version seems to be the "current" LTS release, so in order to use an earlier Node version we have to go back in alpine versions as well

**Comment by iben12** [comment]
True. But in the community repo there's a `nodejs-current` package, that represents the latest non-LTS release. Might be useful.

**Comment by vimtaai** [comment]
I don't know whether the nodejs-current includes older versions as well or not. However I think the current version could work or the node:14-alpine3.14, as it is on the SAP approved list.
Should I update this to use the node:14-alpine3.14? It has an unnecessary yarn installation but I think that's all.

**Comment by iben12** [comment]
Yes, I think we can go with that for the time being.

**Comment by vimtaai** [comment]
@iben12 is this OK now? can we merge this?

**Comment by iben12** [comment]
```
Index of securityapprovedbaseimages/node
Name               Last modified      Size
../
16.8.0-alpine3.13/  01-Sep-2021 02:48    -
16.8.0-alpine3.14/  01-Sep-2021 02:48    -
_uploads/           01-Jul-2021 01:05    -
lts-alpine3.13/     27-Jul-2021 09:41    -
lts-alpine3.14/     27-Jul-2021 09:41    -
```

**Comment by vimtaai** [comment]
I think we should merge this and iterate on it later if needed. Quite a few teams are doing the dockerization right now and this would be helpful for them.

**Pull request merged**
